/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.centromedico.manejo;

/**
 *
 * @author chejo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
     private Pacientes pacientes = new Pacientes(this);
     public Doctores doctores = new Doctores(this);
     Autenticacion aut = new Autenticacion(this);
    
    public Inicio() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_principal = new javax.swing.JPanel();
        btn_pacientes = new javax.swing.JButton();
        btn_doctores = new javax.swing.JButton();
        btn_citas = new javax.swing.JButton();
        btn_reportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));

        pnl_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pacientes.setText("Pacientes");
        btn_pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pacientesActionPerformed(evt);
            }
        });
        pnl_principal.add(btn_pacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        btn_doctores.setText("Doctores");
        btn_doctores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doctoresActionPerformed(evt);
            }
        });
        pnl_principal.add(btn_doctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 80, -1));

        btn_citas.setText("Citas");
        pnl_principal.add(btn_citas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 80, -1));

        btn_reportes.setText("Reportes");
        pnl_principal.add(btn_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pacientesActionPerformed
        this.setVisible(false);
        pacientes.setVisible(true);
    }//GEN-LAST:event_btn_pacientesActionPerformed

    private void btn_doctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doctoresActionPerformed
        this.setVisible(false);
        aut.setVisible(true);
    }//GEN-LAST:event_btn_doctoresActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_citas;
    private javax.swing.JButton btn_doctores;
    private javax.swing.JButton btn_pacientes;
    private javax.swing.JButton btn_reportes;
    private javax.swing.JPanel pnl_principal;
    // End of variables declaration//GEN-END:variables
}
